pub mod fill_rule;
pub mod line_join;
pub mod mask_mode;
pub mod stroke_dash_type;
// todo line-cap
// todo trim-multiple-shapes
// todo font-path-origin
// todo text-justify
// todo text-shape
// todo shape-direction
// todo text-based
// todo gradient-type
// todo matte-mode
// todo blend-mode
// todo text-caps
// todo star-type
// todo text-range-units
// todo text-grouping
// todo merge-mode
// todo composite
