pub mod blend_mode;
pub mod fill_rule;
pub mod font_path_origin;
pub mod gradient_type;
pub mod line_cap;
pub mod line_join;
pub mod mask_mode;
pub mod matte_mode;
pub mod shape_direction;
pub mod star_type;
pub mod stroke_dash_type;
pub mod text_based;
pub mod text_caps;
pub mod text_justify;
pub mod text_shape;
pub mod trim_multiple_shapes;
// todo text-range-units
// todo text-grouping
// todo merge-mode
// todo composite
