pub mod animated_property;
pub mod color_value;
pub mod keyframe;
pub mod keyframe_base;
pub mod keyframe_bezier_handle;
pub mod multi_dimensional;
pub mod position;
pub mod shape_keyframe;
pub mod shape_property;
//todo pub mod gradient_colors;
//todo pub mod split_vector;
pub mod position_keyframe;
pub mod value;
